apiVersion: v1
kind: Pod
metadata:
  name: one-pod
  namespace: vignesh-ns
  labels:
    app: one-web
spec:
  containers:
    - name: one-web-container
      image: vignesh8386/my-app:v1.1.0
      ports:
        - containerPort: 80

